version: '3'

services:
  kimu:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '127.0.0.1:27020:27017'

volumes:
  mongo-data: